AWSTemplateFormatVersion: 2010-09-09
Description: Challenge Lab

####
#Parameters
Parameters:
  AmazonLinuxAMIID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

#Resources

Resources:
  ChallengeVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Challenge VPC

# Internet Gateway
  ChallengeIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: ChallengeIGW

#Attach IGW to Challenge VPC
  LabVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ChallengeVPC
      InternetGatewayId: !Ref ChallengeIGW

#Security Group for SSH Access
  ChallengeLabSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      VpcId: !Ref ChallengeVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrBlock: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: ChallengeLabSecurityGroup

# Private Subnet
  ChallengePrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ChallengeVPC
      CidrBlock: 192.168.1.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: AWS::Region
      Tags:
        - Key: Name
          Value: ChallengePrivateSubnet

# EC2 Instance
  LabEc2Instnace:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmazonLinuxAMIID
      InstanceType: t3.micro
      SubnetId: !Ref ChallengePrivateSubnet
      SecurityGroupIds:
        - !Ref ChallengeLabSecurityGroup
      Tags:
        - Key: Name
          Value: LabEc2Instnace